### ISSUE TITLE
Php Validation Warnings need to be solved(0/14)

### ISSUE THREAD

**Issue by weicheng59** [buse2017fall/SoftwareEngineering#32]
Description	Resource	Path	Location	Type
Invalid location of tag (div).	index.php	/Propal/themes/default	line 106	HTML Problem
Invalid location of tag (div).	index.php	/Propal/themes/default	line 183	HTML Problem
Invalid location of tag (input).	index.php	/Propal/themes/default	line 189	HTML Problem
Invalid location of tag (input).	index.php	/Propal/themes/default	line 190	HTML Problem
Invalid location of tag (label).	index.php	/Propal/themes/default	line 133	HTML Problem
No start tag (div).	index.php	/Propal/themes/default	line 324	HTML Problem
Undefined attribute name (autocomplete).	index.php	/Propal/themes/default	line 134	HTML Problem
Undefined attribute name (clear).	index.php	/Propal/themes/default	line 86	HTML Problem
Undefined attribute name (id).	index.php	/Propal/themes/default	line 12	HTML Problem
Undefined attribute name (name).	index.php	/Propal/themes/default	line 188	HTML Problem
Undefined attribute name (submenu).	index.php	/Propal/themes/default	line 263	HTML Problem
Undefined attribute name (submenu).	index.php	/Propal/themes/default	line 289	HTML Problem
Undefined attribute name (submenu).	index.php	/Propal/themes/default	line 290	HTML Problem
Unknown tag (u).	index.php	/Propal/themes/default	line 79	HTML Problem

**Comment by buse2017fall** [comment]
That's a good suggestion !

Since we have limited time, we can solve those issues later because those are just warnings which have no strong effect on the use of our web application.

**Comment by weicheng59** [comment]
I would totally agree. We spent so many time in testing in this iteration haha.
